#!/usr/bin/env bash

set -eu

repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
remote_name="origin"
main_branch="master"
target_branch="master"

cd "$GITHUB_WORKSPACE"

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"

git checkout "$target_branch"
git rebase "${remote_name}/${main_branch}"

npm install drive-db
npm install node-fetch

node sheet-to-json.js
node sheet-to-json_travel_history.js
node sheet-to-json_raw_data.js
node raw_data-to-state_district_wise_data.js
node sheet-to-json_faq.js

git add state_wise_raw.json data.json travel_history.json raw_data.json state_district_wise_raw.json faq.json
set +e  # Grep succeeds with nonzero exit codes to show results.
git status | grep 'new file\|modified'
if [ $? -eq 0 ]
then
    set -e
    git commit -am "data updated on - $(date)"
    git remote set-url "$remote_name" "$repo_uri" # includes access token
    git push --force-with-lease "$remote_name" "$target_branch"
else
    set -e
    echo "No changes since last run"
fi

echo "finish"
